version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postrgres
